-- CreateTable
CREATE TABLE "Enderecos" (
    "END_ID" SERIAL NOT NULL,
    "CEP" TEXT NOT NULL,
    "UF" TEXT NOT NULL,
    "CIDADE" TEXT NOT NULL,
    "COMPLEMENTO" TEXT,
    "NUMERO" TEXT NOT NULL,
    "ENDEROCO" TEXT NOT NULL,
    "BAIRRO" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Enderecos_pkey" PRIMARY KEY ("END_ID")
);
